#!/usr/bin/env bash
# Builds packlight's history for ha-branch-verdict-11: feat/aws-staging is one
# commit of SST scaffolding off an old main; main has since moved 11 commits on,
# including a script-based AWS deploy. Runs inside the sandbox after its first
# commit. Deterministic: fixed identities and dates.
set -euo pipefail
# The sandbox's first commit carries today's date; back-date it so the history
# below is never older than its own root (clock skew breaks `git rev-list A..B`).
GIT_COMMITTER_DATE="2026-07-01T09:00:00Z" git -c user.name=sandbox -c user.email=sandbox@local \
  commit -q --amend --no-edit --date="2026-07-01T09:00:00Z"
export GIT_AUTHOR_NAME="Packlight Dev" GIT_AUTHOR_EMAIL="dev@packlight.example"
export GIT_COMMITTER_NAME="Packlight Dev" GIT_COMMITTER_EMAIL="dev@packlight.example"
n=0
commit() { # commit <message>; dates step a day from 2026-09-01
  n=$((n + 1))
  GIT_AUTHOR_DATE="2026-09-$(printf %02d $((n < 29 ? n : 28)))T10:00:00Z"
  export GIT_AUTHOR_DATE GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"
  git add -A && git commit -q -m "$1"
}
git branch -M main

# --- the branch: SST scaffolding only, off the first commit ---
git switch -q -c feat/aws-staging
cat > sst.config.ts <<'EOF'
/// <reference path="./.sst/platform/config.d.ts" />
export default $config({
  app(input) {
    return { name: "packlight", home: "aws", removal: input?.stage === "production" ? "retain" : "remove" };
  },
  async run() {
    new sst.aws.Nextjs("Web", { environment: { DATABASE_URL: process.env.DATABASE_URL ?? "" } });
  },
});
EOF
cat > sst-env.d.ts <<'EOF'
/* This file is auto-generated by SST. Do not edit. */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Web": { "type": "sst.aws.Nextjs"; "url": string }
  }
}
EOF
mkdir -p .github/workflows
cat > .github/workflows/aws-staging.yml <<'EOF'
name: AWS staging
on:
  push:
    branches: [feat/aws-staging]
permissions:
  contents: read
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm sst deploy --stage staging
EOF
commit "feat: AWS staging environment via SST"

# --- main moves on: 11 commits ---
git switch -q main
cat >> src/lib/trips.ts <<'EOF'

export function tripLengthDays(trip: Trip): number {
	return Math.round((Date.parse(trip.end) - Date.parse(trip.start)) / 86_400_000) + 1;
}
EOF
commit "feat(trips): trip length helper (#31)"
cat > src/lib/activities.ts <<'EOF'
export const ACTIVITY_ITEMS: Record<string, string[]> = {
	hiking: ["boots", "water bottle", "first-aid kit"],
	beach: ["swimsuit", "sunscreen", "towel"],
	business: ["laptop", "charger", "blazer"],
};

export function itemsForActivities(activities: string[]): string[] {
	return [...new Set(activities.flatMap((a) => ACTIVITY_ITEMS[a] ?? []))];
}
EOF
commit "feat: activity-based packing items (#33)"
mkdir -p "src/app/trips/[id]"
cat > "src/app/trips/[id]/page.tsx" <<'EOF'
export default function TripPage({ params }: { params: { id: string } }) {
	return <main>Trip {params.id}</main>;
}
EOF
commit "feat: trip detail page (#34)"
mkdir -p scripts
cat > scripts/deploy-aws.sh <<'EOF'
#!/usr/bin/env bash
# Deploys packlight to AWS: builds the standalone server, syncs static assets to
# S3 and rolls the ECS service. Replaces the Vercel deploy (see docs/deploy.md).
set -euo pipefail
stage="${1:?usage: deploy-aws.sh <staging|production>}"
pnpm build
aws s3 sync .next/static "s3://packlight-${stage}-static/_next/static" --delete
aws ecs update-service --cluster "packlight-${stage}" --service web --force-new-deployment
EOF
chmod +x scripts/deploy-aws.sh
commit "feat(deploy): script-based AWS deploy (#36)"
mkdir -p .github/workflows docs
cat > .github/workflows/deploy.yml <<'EOF'
name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - run: ./scripts/deploy-aws.sh staging
EOF
commit "ci: deploy staging on push to main (#37)"
cat > docs/deploy.md <<'EOF'
# Deploying packlight

Staging deploys on every push to `main` via `.github/workflows/deploy.yml`,
which runs `scripts/deploy-aws.sh staging`. Production is a manual
`workflow_dispatch` of the same script. SST was evaluated and dropped: the
script is enough for one service and keeps state out of a framework.
EOF
commit "docs: deploy runbook (#38)"
git rm -q vercel.json
commit "chore: remove vercel.json now that AWS serves production (#39)"
sed -i.bak 's/Deployed on Vercel today./Deployed on AWS (see docs\/deploy.md)./' README.md && rm README.md.bak
commit "docs: README deploy line (#40)"
cat >> src/lib/packing.ts <<'EOF'

export function mergeLists(...lists: string[][]): string[] {
	return [...new Set(lists.flat())].sort();
}
EOF
commit "feat(packing): merge weather and activity lists (#42)"
cat > src/lib/share.ts <<'EOF'
export function shareUrl(tripId: string, base = "https://packlight.example"): string {
	return `${base}/t/${encodeURIComponent(tripId)}`;
}
EOF
commit "feat: share a packing list by link (#43)"
cat > src/lib/share.test.ts <<'EOF'
import assert from "node:assert/strict";
import { test } from "node:test";
import { shareUrl } from "./share.ts";

test("share urls are encoded", () => {
	assert.equal(shareUrl("a b"), "https://packlight.example/t/a%20b");
});
EOF
commit "test: share link (#44)"

# --- a local stand-in for the GitHub remote ---
origin="$(pwd)/.git/fixture-origin.git"
git clone -q --bare . "$origin"
git remote add origin "$origin"
git fetch -q origin
git branch -q --set-upstream-to=origin/main main
git switch -q main
