name: checks
on: [pull_request, push]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
