name: checks
on: [pull_request, push]
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
